//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Call
    {
        [Key]
        public int ID { get; set; }
        public string Case_Number { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Description { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Case_Status { get; set; }
        public string CallTypes { get; set; }
        public Nullable<int> SLA { get; set; }
        public Nullable<System.DateTime> DateTimeStampSent { get; set; }
    }
}
