//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class COMPLAINT
    {
        [Key]
        public int COMPNO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string GISKEY { get; set; }
        public string MYTEXT { get; set; }
    }
}
