//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comp
    {
        [Key]
        public decimal COMPNO { get; set; }
        public System.DateTime CRDATE { get; set; }
        public int CRHOURS { get; set; }
        public short CRMIN { get; set; }
        public decimal CRSEC { get; set; }
        public System.DateTime CCDATE { get; set; }
        public short CCHOURS { get; set; }
        public short CCMIN { get; set; }
        public decimal CCSEC { get; set; }
        public System.DateTime CWDATE { get; set; }
        public int CWHOURS { get; set; }
        public short CWMIN { get; set; }
        public decimal CWSEC { get; set; }
        public string HOWREC { get; set; }
        public string NAME { get; set; }
        public string TEL { get; set; }
        public string TELHOME { get; set; }
        public string TDESC { get; set; }
        public string TOWN { get; set; }
        public string STAND { get; set; }
        public string PORTION { get; set; }
        public short LEAD { get; set; }
        public string ADDNO { get; set; }
        public string ADDSTREET { get; set; }
        public string FAULT_DESC { get; set; }
        public string URGENCY { get; set; }
        public string COMMENT { get; set; }
        public string CORNER_A { get; set; }
        public string TIMESHEET_ { get; set; }
        public decimal MAN_ { get; set; }
        public string STATUS { get; set; }
        public string DEPT { get; set; }
        public string TEAM { get; set; }
        public string TS_BACK { get; set; }
        public System.DateTime TS_DATE { get; set; }
        public string ACCOUNT { get; set; }
        public string CUMETER { get; set; }
        public string PLACEMENT_NO { get; set; }
        public string PROPREF { get; set; }
        public string AREA { get; set; }
        public string INSTALL_TYPE { get; set; }
        public string ACTION_CODE { get; set; }
        public string TEST_TIME { get; set; }
        public string COMMENTS_NEW { get; set; }
        public string PAGENO { get; set; }
        public string CRTIME { get; set; }
        public string CWTIME { get; set; }
        public string OPERATOR { get; set; }
        public string SEWMAIN { get; set; }
        public string SEWSTAND { get; set; }
        public string ACCEPT_CHARGE { get; set; }
        public string PRINT_FLAG { get; set; }
        public string EMAIL_FLAG { get; set; }
        public System.DateTime EMAIL_ON { get; set; }
        public string EMAIL_TIME { get; set; }
        public string FAX_FLAG { get; set; }
        public System.DateTime FAX_ON { get; set; }
        public string FAX_TIME { get; set; }
        public string CCTIME { get; set; }
        public System.DateTime CFDATE { get; set; }
        public string CFTIME { get; set; }
        public string FRONT_DESK { get; set; }
        public string URGENT { get; set; }
        public string PLANT_ASSET { get; set; }
        public string SMS_FLAG { get; set; }
        public System.DateTime SMS_ON { get; set; }
        public string LETTER_FLAG { get; set; }
        public System.DateTime LETTER_ON { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string FAX_NUMBER { get; set; }
        public string VACUM { get; set; }
        public string CCDPERS { get; set; }
        public string CFDPERS { get; set; }
        public decimal GISKEY { get; set; }
        public System.DateTime PARK_DATE { get; set; }
        public string PARK_PERS { get; set; }
        public string ORIGINAL { get; set; }
        public decimal SEWTANKKEY { get; set; }
        public decimal PAYMENT_AMOUNT { get; set; }
        public string PAYMENT_RECIEPT { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
        public decimal JC_SORT { get; set; }
    }
}
