//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class emis_mobile_gps
    {
        [Key]
        public int ID { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<int> IMEI_Num { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
    }
}
