//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class emis_mobile_devices_allocation
    {
        [Key]
        public decimal id { get; set; }
        public string TOWNSHIP { get; set; }
        public string DEPT { get; set; }
        public string AREA { get; set; }
        public string STANDBY_CELL_T { get; set; }
        public string STANDBY_CELL_S { get; set; }
        public string Dispatch_YN { get; set; }
        public string SUB_AREA { get; set; }
        public string EMAIL_1 { get; set; }
        public string EMIS_2 { get; set; }
        public string SEND_EMAIL { get; set; }
        public string DAYTIME_CELL { get; set; }
        public string DAYTIME_AREA { get; set; }
        public string STANDBY_S_MAC { get; set; }
        public string STANDBY_T_MAC { get; set; }
        public string DAYTIME_MAC { get; set; }
        public string DISTRICT { get; set; }
    }
}
