//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class emis_mobile_locationlogger
    {
        [Key]
        public string DeviceID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.DateTime Inserted { get; set; }
    }
}
