//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class eMis_Mobile
    {
        [Key]
        public int Cntrl_num { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public string Fault { get; set; }
        public string Township { get; set; }
        public string Stand { get; set; }
        public string Street { get; set; }
        public string Street_No { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Recieved_HD { get; set; }
        public Nullable<System.DateTime> Receive_DateT { get; set; }
        public Nullable<System.DateTime> Start_DateT { get; set; }
        public Nullable<System.DateTime> Delay_DateT { get; set; }
        public Nullable<System.DateTime> Completed_DateT { get; set; }
        public Nullable<System.TimeSpan> Escalation_Time { get; set; }
        public string Assigned_unit_Mac { get; set; }
        public string Completed_Desc { get; set; }
        public string Delayed_Desc { get; set; }
        public Nullable<decimal> Revison { get; set; }
        public string Data_Changed { get; set; }
        public string Client_Mun { get; set; }
    }
}
