//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class emis_notifications
    {
        [Key]
        public int id { get; set; }
        public string device_id { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public string flag { get; set; }
    }
}
