//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class emis_mobile_devices
    {
        [Key]
        public string id { get; set; }
        public string status { get; set; }
        public Nullable<int> reload_time { get; set; }
        public string Department { get; set; }
        public Nullable<int> Record { get; set; }
        public string Update { get; set; }
        public string Area { get; set; }
        public string Client_Mun { get; set; }
        public string Device_Desc { get; set; }
        public string Sup_Mac { get; set; }
        public string UseWifiOnly4Photos { get; set; }
    }
}
