//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HM_Devices
    {
        [Key]
        public string DeviceID { get; set; }
        public string Municipality { get; set; }
        public string Department { get; set; }
        public string Status { get; set; }
        public string GCMToken { get; set; }
        public string TransactionURL { get; set; }
        public Nullable<int> TransactionPort { get; set; }
        public string SettingsURL { get; set; }
        public Nullable<int> SettingsPort { get; set; }
        public int Reading1RangeMin { get; set; }
        public int Reading1RangeMax { get; set; }
    }
}
