//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HM_HandyManReadings
    {
        [Key]
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public string MeterNumber { get; set; }
        public string Township { get; set; }
        public string Stand { get; set; }
        public string Portion { get; set; }
        public string StreetNo { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> Reading1 { get; set; }
        public Nullable<int> Reading2 { get; set; }
        public string NoReadingReason { get; set; }
        public string FaultReason { get; set; }
        public string Status { get; set; }
        public System.DateTime Updated { get; set; }
        public System.DateTime Inserted { get; set; }
        public byte[] Checksum { get; set; }
        public Nullable<int> Reading1MinRange { get; set; }
        public Nullable<int> Reading1MaxRange { get; set; }
    }
}
