//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class M_Dash_Totals
    {
        public string DEPT { get; set; }
        public Nullable<int> Total_Jobs { get; set; }
        public Nullable<int> Jobs_Over { get; set; }
        public Nullable<int> Jobs_in_Time { get; set; }
        [Key]
        public int ID { get; set; }
        public string Job_Type { get; set; }
        public Nullable<int> Jobs_no_Response_Time { get; set; }
        public Nullable<int> Open_Jobs_inside_response_time_framework { get; set; }
        public Nullable<int> Open_Jobs_outside_response_time_framework { get; set; }
    }
}
