//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int reportId { get; set; }
        public string reportName { get; set; }
        public string reportDescription { get; set; }
        public Nullable<int> parentReportId { get; set; }
        public string reportPath { get; set; }
        public string reportIcon { get; set; }
    }
}
