//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class spJobControl_Result1
    {
        public string Device_Desc { get; set; }
        public Nullable<int> JobsAlocated { get; set; }
        public int JobsReceived { get; set; }
        public string Department { get; set; }
        [Key]
        public string Assigned_unit_Mac { get; set; }
        public string Area { get; set; }
        public Nullable<int> Cntrl_num { get; set; }
    }
}
