//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SQL_DASH
    {
        [Key]
        public decimal CTRL { get; set; }
        public System.DateTime? CRDATE { get; set; }
        public string CRTIME { get; set; }
        public System.DateTime? CWDATE { get; set; }
        public string CWTIME { get; set; }
        public string STATUS { get; set; }
        public System.DateTime? STATUS_DATE { get; set; }
        public string DEPT { get; set; }
        public string FAULT_TYPE { get; set; }
        public string AREA { get; set; }
        public string GISKEY { get; set; }
        public string TOWNSHIP { get; set; }
        public decimal RESPONSE_TIME { get; set; }
    }
}
