//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMIS_Reporting_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMSEntities : DbContext
    {
        public WMSEntities()
            : base("name=WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Report_Data> Report_Data { get; set; }
        public virtual DbSet<BO_User> BO_User { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Finance_Demo> Finance_Demo { get; set; }
        public virtual DbSet<Finance_Demo2> Finance_Demo2 { get; set; }
        public virtual DbSet<M_Dash_Totals> M_Dash_Totals { get; set; }
        public virtual DbSet<SQL_DASH> SQL_DASH { get; set; }
    
        public virtual ObjectResult<spGetReferenceNumber_Result> spGetReferenceNumber(string cTRL)
        {
            var cTRLParameter = cTRL != null ?
                new ObjectParameter("CTRL", cTRL) :
                new ObjectParameter("CTRL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetReferenceNumber_Result>("spGetReferenceNumber", cTRLParameter);
        }
    
        public virtual ObjectResult<spGetUserByEmailPassword_Result> spGetUserByEmailPassword(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUserByEmailPassword_Result>("spGetUserByEmailPassword", usernameParameter, passwordParameter);
        }
    }
}
